name = "aoc-slack-notifier"
type = "javascript"
account_id = "YOUR_ACCOUNT_ID"
main = "./src/index.ts"
workers_dev = true
compatibility_date = "2024-11-06"

[env.production]
vars = { AOC_SESSION_TOKEN = "<your_session_token_placeholder>", AOC_LEADERBOARD_ID = "<your_leaderboard_id_placeholder>", SLACK_WEBHOOK_URL = "<your_slack_webhook_placeholder>" }

[env.dev]
vars = { AOC_SESSION_TOKEN = "<local_session_token>", AOC_LEADERBOARD_ID = "<local_leaderboard_id>", SLACK_WEBHOOK_URL = "<local_slack_webhook>" }

[triggers]
crons = ["0 12 * * *"] # Daily trigger